<?php
/**
 * MerchantUrlsTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FormsmedjanKlarnaCheckout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Checkout API V3
 *
 * API spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FormsmedjanKlarnaCheckout\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MerchantUrlsTest Class Doc Comment
 *
 * @category    Class
 * @description MerchantUrls
 * @package     FormsmedjanKlarnaCheckout
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MerchantUrlsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MerchantUrls"
     */
    public function testMerchantUrls()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "terms"
     */
    public function testPropertyTerms()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "checkout"
     */
    public function testPropertyCheckout()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "confirmation"
     */
    public function testPropertyConfirmation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "push"
     */
    public function testPropertyPush()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "validation"
     */
    public function testPropertyValidation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "notification"
     */
    public function testPropertyNotification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cancellation_terms"
     */
    public function testPropertyCancellationTerms()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipping_option_update"
     */
    public function testPropertyShippingOptionUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "address_update"
     */
    public function testPropertyAddressUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "country_change"
     */
    public function testPropertyCountryChange()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
